export const myImage = "https://i.ibb.co/QMrLNqr/IMG-20230322-230227-455.jpg";
export const intro = `MEET ABHISHEK, A VISIONARY WEB DEVELOPER WEAVING DIGITAL WONDERS ONE LINE OF CODE AT A
                        TIME. WITH A PASSION FOR CRAFTING IMMERSIVE ONLINE EXPERIENCES, ABHISHEK
                        BLENDS CREATIVITY WITH CUTTING-EDGE TECHNOLOGY TO SCULPT DYNAMIC
                        WEBSITES THAT CAPTIVATE AND INSPIRE. EXPLORE THE DIGITAL REALM THROUGH
                        ABHISHEK'S LENS, WHERE INNOVATION MEETS ELEGANCE.`;

export const intro2 = `STEP INTO A REALM OF DIGITAL ENCHANTMENT WHERE I WEAVE WEBS OF WONDER. 
FROM CRAFTING CAPTIVATING DESIGNS TO CODING WITH FINESSE, 
I BREATHE LIFE INTO YOUR ONLINE PRESENCE. LET ME GUIDE YOU THROUGH 
THE MAZE OF TECHNOLOGY, WHERE EVERY PIXEL TELLS A STORY OF INNOVATION AND ELEGANCE.`;
